/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const pdffiles_Logic = require('./code/pdffiles-logic');
const extractfromimage_Logic = require('./code/extractfromimage-logic');

class pdfreaderService extends LCAPApplicationService {
    async init() {

        this.on('CREATE', 'pdfFiles', async (request, next) => {
            return pdffiles_Logic(request, next);
        });

        this.on('extractFromImage', async (request) => {
            return extractfromimage_Logic(request);
        });

        return super.init();
    }
}


module.exports = {
    pdfreaderService
};